### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Nithmr/HostelAllotment#5]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by ibonly** [comment]
I've never work with CAKEPHP but I'll like to give this a shot!!!

**Comment by Rishabh04-02** [comment]
@andela-iadeniyi Thanks for showing your interest, ping me when need any help.

**Comment by MayMeow** [comment]
I  ❤️  CakePHP... i can create Readme for you

**Comment by Rishabh04-02** [comment]
@MayMeow Thanks for contributing 👍. But @andela-iadeniyi bid first for the issue, so if he hasn't completed the issue then we'll merge your PR, else we have to go with his PR.

**Comment by MayMeow** [comment]
@Rishabh04-02 ok np :) if he was first merge his PR

**Comment by Rishabh04-02** [comment]
@MayMeow @andela-iadeniyi Thanks for contributing 👍.
